plugins {
    id 'com.android.application'
}

android {
    namespace 'it.atlanticfluidtech.aftwebbrowser'
    compileSdk 35

    defaultConfig {
        applicationId "it.atlanticfluidtech.aftwebbrowser"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "2.0"
    }
}
